module "deploy_vcenter" {
  source                = "kalenarndt/vcsa-deploy/vsphere"
  deploy_type           = "esxi"
  esxi_hostname         = "192.168.200.66"
  esxi_username         = "root"
  esxi_password         = "Test1234!"
  vcsa_network          = "MGMT"
  vcsa_datastore        = "datastore1"
  deployment_size       = "tiny"
  vcenter_hostname      = "vmvc01.pauky.eu"
  vcenter_fqdn          = "vmvc01.pauky.eu"
  vcenter_ip            = "192.168.200.67"
  vcenter_prefix        = "24"
  vcenter_gateway       = "192.168.200.254"
  vcenter_dns           = "192.168.200.254"
  vcenter_root_password = "VMware123!"
  vcenter_ntp_server    = "pool.ntp.org"
  binaries_path         = "/images/vcenter"
}

