module "deploy_vcenter" {
  source = "kalenarndt/vcsa-deploy/vsphere"

  deploy_type           = "vc"
  vc_datacenter         = "Black Mesa"
  vc_username           = "administrator@vsphere.local"
  vc_hostname           = "vc.bmrf.io"
  vc_password           = "VMware123!"
  vc_cluster            = "Compute"
  vcsa_network          = "Sector-B-VL21"
  vcsa_datastore        = "ESXi2-SSD"
  deployment_size       = "small"
  vcenter_hostname      = "vc-sb.bmrf.io"
  vcenter_fqdn          = "vc-sb.bmrf.io"
  vcenter_ip            = "172.16.21.10"
  vcenter_prefix        = "24"
  vcenter_gateway       = "172.16.21.1"
  vcenter_dns           = "172.16.11.2"
  vcenter_root_password = "VMware123!"
  vcenter_ntp_server    = "time.bmrf.io"
  binaries_path         = "/binaries/vcsa"
}
